name: "mkhouse-rabbitmq"

services:

  mkhouse-rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "mkhouse-rabbitmq"
    hostname: "mkhouse-rabbitmq"
    restart: "unless-stopped"
    dns:
      - "1.1.1.1"
      - "4.4.4.4"
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "America/Sao_Paulo"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - mkhouse-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - "mkhouse-rabbitmq-net"
      - "mkhouse-vpc-net"

networks:
  mkhouse-rabbitmq-net:
    external: true
  mkhouse-vpc-net:
    external: true

volumes:
  mkhouse-rabbitmq-data:
    external: true
