name: "Deploy RabbitMQ"
run-name: "${{ github.event_name }} by ${{ github.actor }} #${{ github.run_number }}.${{ github.run_attempt }}"

on:
  push:
    branches:
      - "main"

jobs:
  deploy-rabbitmq:
    name: "Deploy RabbitMQ"
    runs-on:
      - "self-hosted"
    env:
      ANSIBLE_PROJECT: "${{ vars.ANSIBLE_PROJECT }}"
      RABBITMQ_PROJECT: "${{ vars.RABBITMQ_PROJECT }}"
      RABBITMQ_DEFAULT_USER: "${{ vars.RABBITMQ_DEFAULT_USER }}"
      RABBITMQ_DEFAULT_PASS: "${{ secrets.RABBITMQ_DEFAULT_PASS }}"
      CF_ACCOUNT_ID: "${{ secrets.CF_ACCOUNT_ID }}"
      CF_ACCOUNT_EMAIL: "${{ secrets.CF_ACCOUNT_EMAIL }}"
      CF_TUNNEL_API_TOKEN: "${{ secrets.CF_TUNNEL_API_TOKEN }}"
      CF_TUNNEL_ID: "${{ secrets.CF_TUNNEL_ID }}"
      CF_SERVICE: "${{ vars.CF_SERVICE }}"
      CF_HOSTNAME: "${{ vars.CF_HOSTNAME }}"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v2"
      - name: "Copy project to dropfolder"
        run: |
          sudo rm -rf ${ANSIBLE_PROJECT}/_dropfolder/rabbitmq/*
          sudo mkdir -p ${ANSIBLE_PROJECT}/_dropfolder/rabbitmq
          sudo chmod 0755 ${ANSIBLE_PROJECT}/_dropfolder/rabbitmq
          sudo cp -r ./docker/* ${ANSIBLE_PROJECT}/_dropfolder/rabbitmq/
      - name: "Run Ansible Playbook"
        run: |
          ansible-playbook ./ansible/playbooks/deploy-rabbitmq.yml \
            -i ${ANSIBLE_PROJECT}/inventory/hosts.ini \
            -e ANSIBLE_PROJECT=${ANSIBLE_PROJECT} \
            -e RABBITMQ_PROJECT=${RABBITMQ_PROJECT} \
            -e RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER} \
            -e RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS} \
            -e CF_ACCOUNT_ID=${CF_ACCOUNT_ID}" \
            -e CF_ACCOUNT_EMAIL=${CF_ACCOUNT_EMAIL}" \
            -e CF_TUNNEL_API_TOKEN=${CF_TUNNEL_API_TOKEN}" \
            -e CF_TUNNEL_ID=${CF_TUNNEL_ID}" \
            -e CF_SERVICE=${CF_SERVICE}" \
            -e CF_HOSTNAME=${CF_HOSTNAME}"
