name: "Deploy RabbitMQ"
run-name: "${{ github.event_name }} by ${{ github.actor }} #${{ github.run_number }}.${{ github.run_attempt }}"

on:
  push:
    branches:
      - "main"

env:
  ANSIBLE_PROJECT: "${{ vars.ANSIBLE_PROJECT }}"
  RABBITMQ_PROJECT: "${{ vars.RABBITMQ_PROJECT }}"
  RABBITMQ_DEFAULT_USER: "${{ vars.RABBITMQ_DEFAULT_USER }}"
  RABBITMQ_DEFAULT_PASS: "${{ secrets.RABBITMQ_DEFAULT_PASS }}"

jobs:
  deploy-rabbitmq:
    name: "Deploy RabbitMQ"
    runs-on:
      - "self-hosted"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v2"
      - name: "Copy project to dropfolder"
        run: |
          sudo rm -rf ${ANSIBLE_PROJECT}/_dropfolder/rabbitmq/*
          sudo mkdir -p ${ANSIBLE_PROJECT}/_dropfolder/rabbitmq
          sudo chmod 0755 ${ANSIBLE_PROJECT}/_dropfolder/rabbitmq
          sudo cp -r ./docker/* ${ANSIBLE_PROJECT}/_dropfolder/rabbitmq/
      - name: "Run Ansible Playbook"
        run: |
          ansible-playbook ./ansible/playbooks/deploy-rabbitmq.yml \
            -i ${ANSIBLE_PROJECT}/inventory/hosts.ini \
            -e ANSIBLE_PROJECT=${ANSIBLE_PROJECT} \
            -e RABBITMQ_PROJECT=${RABBITMQ_PROJECT} \
            -e RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER} \
            -e RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
