name: "Deploy RabbitMQ"
run-name: "${{ github.event_name }} by ${{ github.actor }} #${{ github.run_number }}.${{ github.run_attempt }}"

on:
  push:
    branches:
      - "main"

jobs:

  deploy-cloudflared:
    runs-on:
      - "self-hosted"
      - "tankian"
    env:
      TF_VAR_rabbitmq_default_user: "${{ vars.RABBITMQ_DEFAULT_USER }}"
      TF_VAR_rabbitmq_default_pass: "${{ secrets.RABBITMQ_DEFAULT_PASS }}"
      TF_VAR_docker_volume_basepath: "${{ vars.DOCKER_VOLUME_BASEPATH }}"
      TF_VAR_cloudflare_api_token: "${{ secrets.CF_TUNNEL_API_TOKEN }}"
      TF_VAR_cloudflare_account_id: "${{ secrets.CF_ACCOUNT_ID }}"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v2"
      - name: "Initialize Terraform"
        run: |
          terraform -chdir=./terraform init
      - name: "Plan Terraform configuration"
        run: |
          terraform -chdir=./terraform plan
      - name: "Apply Terraform configuration"
        run: |
          terraform -chdir=./terraform apply -auto-approve
